# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='team_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Problem'),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Team'),
        ),
    ]
